### PR TITLE
fix the new transliteration file

### PR DESCRIPTION
**Pull request by Ashraf-Ali-aa**
- fixed the new transliteration file
- rename old transliteration file for reference

### CODE REVIEW

**Comment by iBasit** [comment]
old transliteration has underscore, dash and bold. Are you sure you want to replace it with new one?

old demo:
http://globalquran.com/en.transliteration+quran-uthmani/1:1

image

Also, if you are sure you want to replace above with new simple text transliteration, then please add meta data info from previous file. it is missing meta data info after 6236 lines.

**Comment by Ashraf-Ali-aa** [comment]
@iBasit I prefer the new transliteration they are more in line with how you would pronounce it (tajweed) i.e Bismillaahir, but we could have both and let the user decide.

**Comment by iBasit** [comment]
ok sure, please fix meta data and notify here.

**Comment by Ashraf-Ali-aa** [comment]
@iBasit that's done

**Comment by iBasit** [comment]
Sorry, but you need to remove old file or remove its meta data..  it will conflict between them. since they have same id, if you change to new id, then it will start showing as new transliteration. 

so its best to remove meta data completely, if you want to keep as reference

**Comment by Ashraf-Ali-aa** [comment]
@iBasit what should I rename it to.

**Comment by iBasit** [comment]
I have edited previous my comment

**Comment by Ashraf-Ali-aa** [comment]
@iBasit ok, I have removed the metadata.

**Pull request merged**
